routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::Routes();

Route::group(['middleware' => ['auth', 'CheckUserStatus']], function () {
    //
});

Route::view('/', 'welcome');

app/Models/User.php
<?php

namespace App\Models;

use App\Crud\Crud;
use App\Traits\UserApi;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, UserApi;

    protected $guarded = ['id'];

    protected $hidden = ['password','remember_token'];

    protected $casts = ['email_verified_at' => 'datetime', 'status' => 'boolean'];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function getImageUrlAttribute()
    {
        return ($this->image != null) ? url('public/uploaded/users/' . $this->image->image) : url('public/admin/img/avatar10.jpg');
    }

    public function setStatusAttribute($value)
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public function token()
    {
        return $this->morphOne(Token::class, 'tokenable');
    }

    public function notifications()
    {
        return $this->morphMany(Notification::class, 'notificationable');
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function fcm()
    {
        return $this->morphOne(Fcm::class,'fcmable');
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public static function getInSelectForm()
    {
        return Crud::getModelsInSelectedForm(self::class,'name');
    }
}

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\Admin;
use App\Models\Role;
use Illuminate\Http\Request;
use App\Exports\AdminsExport;
use Illuminate\Support\Facades\Auth;

class AdminController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('admin', Admin::class, new AdminsExport);
    }

    public function index()
    {
        return view('Back.Admins.index', ['admins' => Admin::where('role_id', '!=', 1)->orWhere('role_id', '=', null)->get()]);
    }

    public function showAdminMessage($id)
    {
        if (!$admin = Admin::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('responseMessages.product-not-exist')]);

        return view('Back.Admins.showAdminMailSendModal', compact('admin'))->render();
    }

    public function sendAdminMessage(Request $request)
    {
        return Admin::sendAdminMessage($request);
    }

    public function showAdmin(Admin $admin)
    {
        return view('Back.Admins.show', compact('admin'));
    }

    public function home()
    {
        return view('Back.index');
    }

    public function AdminUpdateProfile(Requests\Back\EditAdminProfileRequest $request)
    {
        $adminData = $request->except(['_token', 'submit']);

        $currentAdmin = Admin::find($adminData['admin_id']);

        return Admin::updateAdmin(arr()->except($adminData, ['admin_id']), $currentAdmin);
    }

    public function adminProfile()
    {
        return view('Back.Admins.profile', ['admin' => Auth::guard('admin')->user()]);
    }

    public function create()
    {
        return view('Back.Crud.create', ['roles' => Role::getInSelectForm(), 'model' => 'admin']);
    }

    public function store(Requests\Back\CreateAdminRequest $request)
    {
        return Admin::createAdmin($request);
    }

    public function edit($id)
    {
        return view('Back.Crud.edit', ['currentModel' => Admin::findOrFail($id), 'roles' => Role::getInSelectForm(), 'model' => 'admin']);
    }

    public function update(Requests\Back\EditAdminRequest $request, $id)
    {
        return Admin::updateAdmin($request, Admin::find($id));
    }

    public function DeleteAdmin(Request $request)
    {
        return Admin::deleteAdmin($request);
    }
}

app/Http/Controllers/Back/ContactController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\ContactsExport;
use Maatwebsite\Excel\Facades\Excel;

class ContactController extends Controller
{
    public function Contacts()
    {
        return view('Back.Contacts.contacts', ['contacts' => Contact::all()]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('responseMessages.product-not-exist')]);

        return view('Back.Contacts.messageDetailsModal', compact('message'))->render();
    }

    public function sendUserMessage($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('back.message-not-exists')]);

        return view('Back.Contacts.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(Request $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function ContactsExport(Request $request)
    {
        return Excel::download(new ContactsExport, 'contacts.xlsx');
    }

    public function DeleteContact(Request $request)
    {
        return Contact::deleteMessage($request);
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Exports\TrainingsExport;
use App\Models\Training;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;

class DashboardController extends Controller
{
    public function index()
    {
        $users = User::latest()->get();

        return view('Back.index', ['latest_users' => $users->take(4), 'days' => getCollectionBerDayCount($users), 'users' => $users]);
    }

    public function trainings()
    {
        return view('Back.Trainings.index', ['trainings' => Training::all()]);
    }

    public function export(Request $request)
    {
        return Excel::download(new TrainingsExport, 'trainings.xlsx');
    }
}

app/Http/Controllers/Back/RoleController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Role;
use App\Repository\Contracts\IRoleRepository;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected $repo;

    public function __construct(IRoleRepository $repository)
    {
        $this->repo = $repository;
    }

    public function apiIndex()
    {
        return $this->repo->apiIndex();
    }

    public function index()
    {
        return $this->repo->index();
    }

    public function changeStatus(Request $request)
    {
        return $this->repo->changeStatus($request);
    }

    public function create()
    {
        return $this->repo->create();
    }

    public function store(Requests\Back\CreateRoleRequest $request)
    {
        return $this->repo->store($request);
    }

    public function update(Requests\Back\EditRoleRequest $request, $id)
    {
        return $this->repo->update($request, Role::find($id));
    }

    public function delete(Request $request)
    {
        return $this->repo->delete($request);
    }
}

app/Http/Controllers/Back/SettingController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\SettingsExport;
use Maatwebsite\Excel\Facades\Excel;

class SettingController extends Controller
{
    public function index()
    {
        return view('Back.Settings.index', ['settings' => Setting::all()]);
    }

    public function create()
    {
        return view('Back.Settings.create');
    }

    public function export(Request $request)
    {
        return Excel::download(new SettingsExport, 'settings.xlsx');
    }

    public function store(Requests\Back\CreateSettingRequest $request)
    {
        return Setting::createSetting($request);
    }

    public function edit(Setting $setting)
    {
        return view('Back.Settings.edit', compact('setting'));
    }

    public function update(Requests\Back\EditSettingRequest $request, $id)
    {
        return Setting::updateSetting($request, Setting::find($id));
    }

    public function UpdateAll(Request $request)
    {
        return Setting::updateAll($request);
    }
}

app/Http/Controllers/Back/UserController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\User;
use App\Repository\Contracts\IUserRepository;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $repo;

    public function __construct(IUserRepository $repository)
    {
        $this->repo = $repository;
    }

    public function index()
    {
        return $this->repo->index();
    }

    public function apiIndex()
    {
        return $this->repo->apiIndex();
    }

    public function create()
    {
        return $this->repo->create();
    }

    public function edit($id)
    {
        return $this->repo->edit($id);
    }

    public function showUserMessage($id)
    {
        return $this->repo->showUserMessage($id);
    }

    public function changeStatus(Request $request)
    {
        return $this->repo->changeStatus($request);
    }

    public function forceDelete($id)
    {
        return $this->repo->forceDelete($id);
    }

    public function sendUserMessage(Request $request)
    {
        return $this->repo->showUserMessage($request);
    }

    public function sendUserNotification(Request $request)
    {
        return $this->repo->sendUserNotification($request);
    }

    public function show(User $user)
    {
        return view('Back.Users.show', compact('user'));
    }

    public function store(Requests\Back\CreateUserRequest $request)
    {
        return $this->repo->store($request);
    }

    public function update(Requests\Back\EditUserRequest $request, $id)
    {
        return $this->repo->update($request, User::find($id));
    }

    public function delete(Request $request)
    {
        return $this->repo->delete($request->id);
    }
}

app/Http/Controllers/Front/UserController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Repository\Contracts\IUserRepository;

class UserController extends Controller
{
    protected $userRepo;

    public function __construct(IUserRepository $userRepository)
    {
        $this->userRepo = $userRepository;
    }

    public function index()
    {
        return view('front.users.index', ['users' => $this->userRepo->paginate()]);
    }

    public function show($id)
    {
        return view('front.users.show', ['user' => $this->userRepo->find($id)]);
    }
}

resources/views/Back/Users/form.blade.php
<div class="panel panel-flat border-top-success">
    <div class="panel-body">
        <div class="form-group">
            <x-form-inputs type="text" name="name" :slug="trans('back.form-name')"></x-form-inputs>
        </div>

        <div class="form-group">
            <x-form-inputs type="email" name="email" :slug="trans('back.form-email')"></x-form-inputs>
        </div>

        <div class="form-group">
            <x-form-inputs type="tel" name="phone" :slug="trans('back.form-phone')"></x-form-inputs>
        </div>

        @if(Route::is('users.create'))
            <div class="form-group">
                <x-form-inputs type="password" name="password" :slug="trans('back.form-password')"></x-form-inputs>
            </div>
            <div class="form-group">
                <x-form-inputs type="password_confirmation" name="password" :slug="trans('back.form-password')"></x-form-inputs>
            </div>
        @endif

        <div class="form-group">
            <x-form-inputs type="image" name="image" :slug="trans('back.form-image')"></x-form-inputs>

            <div class="col-xs-6">
                <div class="img-container">
                    <img id="viewImage" class="img-responsive" width="90" height="90" src="{{ isset($currentModel) ? $currentModel->image_url : '' }}" alt=""/>
                </div>
            </div>
        </div>

        <div class="form-group">
            <x-switch-input :model="$currentModel ?? null"></x-switch-input>
        </div>
    </div>
</div>

@section('scripts')
    <script>
        $('input[name=image]').on('change', function(){
            readURL(this);
        });
    </script>
@stop

resources/views/Back/Users/index.blade.php
<x-model-index-page model="user" modelType="male">
    <table class="table table-delete-action-now" id="users" style="font-size: 16px;">
        <thead>
        <tr>
            <th>#</th>
            <th>@lang('back.form-name')</th>
            <th>@lang('back.form-phone')</th>
            <th>@lang('back.form-email')</th>
            <th>@lang('back.form-status')</th>
            <th class="text-center">@lang('back.form-actions')</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
    <x-slot name="scripts">
        <script>
            $(document).ready( function () {
                let renderActionColumn = function (data, type, item)
                {
                    let rootPath = '{{request()->root().'/'.app()->getLocale()}}';
                    let editTrans = '@lang('back.edit')';
                    let delTrans = '@lang('back.delete')';
                    let flooting = "{{ floating('right', 'left') }}";

                    return `<ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>

                                <ul class="dropdown-menu dropdown-menu-${flooting}">
                                    <li><a href="${rootPath+'/admin-panel/users/'+item.id+'/edit'}"><i class="icon-database-edit2"></i>${editTrans}</a></li>
                                    <li>
                                        <a data-id="${item.id}" href="javascript:void(0);" class="delete-action">
                                            <i class="icon-database-remove"></i>${delTrans}
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>`;
                };

                let renderName = function (data, type, item){
                    return `<a href="{{localeUrl(request()->root())}}/admin-panel/users/show/${item.id}/">${item.name}</a>`;
                }

                let languages = {
                    "paginate": {
                        "previous": "@lang('pagination.previous')",
                        "next": "@lang('pagination.next')",
                        "first": "@lang('datatables.first')",
                        "last": "@lang('datatables.last')",
                    },
                    "search": "@lang('datatables.search') : ",
                    "infoEmpty": "@lang('datatables.emptyshowing')",
                    "info": "@lang('datatables.showResult')",
                    "emptyTable": "@lang('datatables.no-data-available')",
                    "infoFiltered": "@lang('datatables.infoFiltered')",
                    "zeroRecords": "@lang('datatables.zeroRecords')",
                    "loadingRecords": "&nbsp;",
                    "processing"	: "<i class='fa fa-3x fa-asterisk fa-spin'></i>"
                };

                let ajaxRequest = { url : "{{ route('users.apiIndex') }}", dataSrc : "data"};

                $('table#users').DataTable({
                    "language": languages,
                    processing : true,
                    serverSide : true,
                    autoWidth: false,
                    columnDefs: [
                        { orderable: true, width: '100px', targets: [5] }
                    ],
                    dom: '<"datatable-header"fl><"datatable-scroll"t><"datatable-footer"ip>',
                    ajax : ajaxRequest,
                    columns : [
                        {data: 'id', name: 'id'},
                        {data: 'name', render: renderName},
                        {data: 'phone', name: 'phone'},
                        {data: 'email', name: 'email'},
                        {data: 'status', render: renderStatus},
                        {data: "id", render : renderActionColumn},
                    ],
                    drawCallback: function () {
                        $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').addClass('dropup');
                    },
                    preDrawCallback: function() {
                        $(this).find('tbody tr').slice(-3).find('.dropdown, .btn-group').removeClass('dropup');
                    },
                });

                $('.dataTables_filter input[type=search]').attr('placeholder','@lang('datatables.type-to-filter')');

                $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity, width: 'auto' });
            });

            $(".table-delete-action-now").on("click", ".delete-action", function() {

                let clickedBtn = $(this);
                let datatable = clickedBtn.parents('table').dataTable();
                let id = clickedBtn.data('id');
                let deleteMessage = '{{ trans('back.delete-message-var', ['var' => trans('back.t-user'), 'type' => trans('back.for-male')]) }}';
                let deleteMessageTitle = '{{ trans('back.delete-message-title') }}';
                let ajaxUrl = '{{ route('users.ajax-delete-user') }}';

                swal({title: deleteMessage, text: deleteMessageTitle, icon: "warning", buttons: true, dangerMode: true}).then(willDelete => {
                    if (willDelete) {
                        $.ajax({
                            type: 'POST',
                            url: ajaxUrl,
                            data: { id },
                            success: function(response)
                            {
                                if (response.deleteStatus)
                                {
                                    clickedBtn.parents('tr').fadeOut('slow', () => datatable.fnDeleteRow($(this)));
                                    swal(response.message, {icon: "success"});
                                }
                                else
                                {
                                    swal(response.error);
                                }
                            },
                            error: (x) => crud_handle_server_errors(x)
                        });
                    } else {
                        swal({title: "@lang('back.a-message')", text: "@lang('back.operation-terminated')", icon: "success", button: "@lang('back.ok')"});
                    }
                });
            });
        </script>
    </x-slot>
</x-model-index-page>

resources/views/Back/Users/sendUserMessageModal.blade.php
<div id="view_show_user_send_message" class="modal fade">
    <div class="modal-dialog">
        <form action="{{route('users.send.message')}}" method="post">
            <div class="modal-content" dir="{{direction()}}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h1 class="modal-title">@lang('back.send-a-message')</h1>
                </div>

                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="email" value="{{$user->email}}" id="email">
                    <textarea style="resize: vertical;" name="message" class="form-control" id="message" cols="30" rows="10"></textarea>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">@lang('back.close')</button>
                    <button type="submit" name="submit" class="btn btn-primary">@lang('back.send')</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/Back/Users/show.blade.php
@extends('Back.layouts.master')

@section('title', $user->name)

@section('content')
    <x-page-show-header model="user" :title="$user->name"></x-page-show-header>

    <div class="content">
        <div class="row">
            @include('includes.flash')
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-flat border-top-primary">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3" style="float: {{ floating('right', 'left') }}">
                                <div class="thumbnail">
                                    <div class="thumb">
                                        <img style="width: 300px;height: 200px;" src="{{ $user->image_url }}" alt="">
                                        <div class="caption-overflow">
                                            <span>
                                                <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info btn-sm">@lang('back.edit')</a>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="caption">
                                        <h6 class="text-semibold no-margin-top" title="{{ $user->name }}">
                                            {{ ucwords(str()->limit($user->name, 30, '...')) }}
                                        </h6>
                                    </div>
                                </div>
                                <div class="lead">
                                    <button class="btn btn-success btn-block" data-toggle="modal" data-target="#view_show_user_send_notification">@lang('back.send-notification')
                                        <i class="icon-bell-check"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-9" style="float: {{ floating('left', 'right') }}">
                                <div class="well">
                                    <dl dir="{{ direction() }}">
                                        <dt>@lang('back.form-email')</dt>
                                        <dd>{{ $user->email ?? trans('back.no-value') }}</dd>

                                        <dt>@lang('back.form-phone')</dt>
                                        <dd>{{ $user->mobile ?? trans('back.no-value') }}</dd>

                                        <dt>@lang('back.form-status')</dt>
                                        <dd>
                                            @if($user->status == 1) <span class="label label-success">@lang('back.active')</span>
                                            @else <span class="label label-danger">@lang('back.disactive')</span>
                                            @endif
                                        </dd>

                                        <dt>@lang('back.since')</dt>
                                        <dd>{{ $user->created_at->diffForHumans() }}</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="view_show_user_send_notification" class="modal fade">
        <div class="modal-dialog">
            <form action="{{ route('users.send-notification') }}" method="post">
                <div class="modal-content" dir="{{direction()}}">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h1 class="modal-title">@lang('back.send-a-message')</h1>
                    </div>

                    <div class="modal-body">
                        @csrf
                        <input type="hidden" name="user_id" value="{{ $user->id }}">
                        <div class="form-group @error('title') has-error @enderror">
                            <label for="title">@lang('back.form-title')</label>
                            <input type="text" name="title" id="title" class="form-control">
                            @error('title') <span
                                style="color: #d84315"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                        <div class="form-group @error('title') has-error @enderror">
                            <label for="body">@lang('back.form-body')</label>
                            <input type="text" name="body" id="body" class="form-control">
                            @error('body') <span style="color: #d84315"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link" data-dismiss="modal">@lang('back.close')</button>
                        <button type="submit" name="submit" class="btn btn-primary">@lang('back.send')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/Back/Users/trashed.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.trashed'))

@section('content')
    <x-page-header model="user" type="trashes"></x-page-header>

    <!-- Basic datatable -->
    <div class="panel panel-flat" dir="{{ direction() }}" style="margin: 20px;">
        @include('includes.flash')

        <div class="panel-heading">
            <x-trashed-table-head table="users" :collection="$trashes"></x-trashed-table-head>
        </div>

        <table class="table datatable-basic" id="users" style="font-size: 16px;">
            <thead>
            <tr>
                <th>#</th>
                <th>@lang('back.form-name')</th>
                <th>@lang('back.form-image')</th>
                <th>@lang('back.form-status')</th>
                <th>@lang('back.since')</th>
                <th class="text-center">@lang('back.form-actions')</th>
            </tr>
            </thead>
            <tbody>
            @foreach($trashes as $key => $user)
                <tr id="user-row-{{ $user->id }}">
                    <td>{{ $key+1 }}</td>

                    <td>{{ $user->name ?? trans('back.no-value') }}</td>

                    <td><img width="60" height="60" class="img-circle" src="{{ $user->image_url }}" alt=""></td>

                    <td>
                        @if($user->status == 1)
                            <label class="label label-success">Active</label>
                        @else
                            <label class="label label-danger">Didactive</label>
                        @endif
                    </td>

                    <td>{{ $user->created_at->diffForHumans() }}</td>

                    <td class="text-center">
                        <x-trash-menu table="users" :model="$user"></x-trash-menu>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic datatable -->
@stop